### ISSUE TITLE
Apocalypse Chow is not listed under efficiency

### ISSUE THREAD

**Issue by Therzok** [Corbeno/Idleon-Insight-Frontend#1]
If you search for: [cooking efficiency](https://idleoninsight.com/?search=Cooking%20efficiency) or [cooking exp](
https://idleoninsight.com/?search=Cooking%20exp) you get these results.

From the looks of it, some cooking stuff is typo'd `Efficncy` or just `eff`. Could the search correct typos or use something like levenshtein distance when matching?

**Comment by Corbeno** [comment]
Currently the search uses regex matching, which allows for an exclusion and more detailed searching. It might be worth investigating this approach, as it makes it easier for the end user. That being said, I created custom searches in the top right corner to allow for more complex searches to be auto filled. For example, the cooking eff search uses "cooking.*eff" which gets allows for efficiency, efficncy, and eff to all match.

It's obviously not a 100% perfect approach, as things change,  but if you find any of the custom searches are wrong/could be improved feel free to make a PR or submit another issue and I can make the changes myself.
