### ISSUE TITLE
amethyst Rhinestone

### ISSUE THREAD

**Issue by BanceSt** [Corbeno/Idleon-Insight-Frontend#2]
if you search for cooking speed, amethyst Rhinestone is not listed

**Comment by Corbeno** [comment]
I updated the custom search in this [commit](https://github.com/Corbeno/Idleon-Insight-Frontend/commit/e8cbf6508af385a75e463818891b2a2381e54eba).

Thank you for finding this! Reports like this are invaluable to this site!
