### ISSUE TITLE
Tool Upgrade Stones gives Weapon Power

### ISSUE THREAD

**Issue by BHY4A** [Corbeno/Idleon-Insight-Frontend#3]
Tool Upgrade Stones says that it gives Weapon Power but it's not

![изображение](https://user-images.githubusercontent.com/33008019/217588936-24a1bce4-2f09-4682-b170-cd4753202ca2.png)

**Comment by Corbeno** [comment]
Sorry for the delay. Must have missed the notification about this. I'll look into it shortly. Thank you for reporting!

**Comment by Corbeno** [comment]
Fixed in wiki bot. Thanks again for reporting
