### ISSUE TITLE
Missing space in 'No Bubble Left Behind' Merit shop upgrade

### ISSUE THREAD

**Issue by ninjaloose** [Corbeno/Idleon-Insight-Frontend#7]
<html><body>

Merit Shop | Upgrade: 30 | + Bubbles upgraded by 'No Bubble LeftBehind' per day. Bubble blowin' baby!
-- | -- | --

</body>
</html>

Should read

<html><body>

Merit Shop | Upgrade: 30 | + Bubbles upgraded by <B>'No Bubble Left Behind'</B> per day. Bubble blowin' baby!
-- | -- | --

</body>
</html>

**Comment by Corbeno** [comment]
nice catch! Turns out it was happening for all merit shop upgrades. Simple fix on my end. Good eye!
