### ISSUE TITLE
Family Bonuses are not included

### ISSUE THREAD

**Issue by Trinn-0** [Corbeno/Idleon-Insight-Frontend#8]
Family bonuses, 
like Elemental Sorcerer's "+0 Lv For All Talents Above Lv 1" 
or Siege Breaker's "+0% Faster Minimum Boat Travel Time"
are not included in the searchable features. It would be great if all family bonuses were added.

**Comment by Corbeno** [comment]
Added! Never noticed that, thanks for pointing it out!
